### ISSUE TITLE
Fails with DHCP

### ISSUE THREAD

**Issue by charles-rose** [nhorman/redfish-finder#2]
On a Dell PowerEdge R740, redfish-finder fails when Host IP Assignment Type is "DHCP".

[root@dev redfish-finder]# dmidecode -t42
# dmidecode 3.2
Getting SMBIOS data from sysfs.
SMBIOS 3.2.0 present.

Handle 0x2A00, DMI type 42, 118 bytes
Management Controller Host Interface
        Host Interface Type: Network
        Device Type: USB
                idVendor: 0x413c
                idProduct: 0xa102
                Protocol ID: 04 (Redfish over IP)
                        Service UUID: Not Settable
                        Host IP Assignment Type: DHCP
                        Host IP Address Format: IPv4
                        Redfish Service IP Discovery Type: Static
                        Redfish Service IP Address Format: IPv4
                        IPv4 Redfish Service Address: 169.254.2.2
                        IPv4 Redfish Service Mask: 255.255.255.0
                        Redfish Service Port: 443
                        Redfish Service Vlan: 4294967295
                        Redfish Service Hostname: idrac.local

[root@dev redfish-finder]# ./redfish-finder
redfish-finder: Getting dmidecode info
Error parsing dmidecode information: redfish-finder: Unexpected error while parsing HostConfig!

**Comment by charles-rose** [comment]
Here is a fix:
https://github.com/nhorman/redfish-finder/pull/3

**Comment by nhorman** [comment]
comitted , thanks!
